
# 06/19/2021 07:45 am - SSN - Parts from different sources

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: ssn-self-hosted-pool-20210604

variables:
  buildConfiguration: Release
  RestoreBuildProjects: '**/DevSitesIndex.csproj'
  WebAppName: DevSitesIndex20190127
# 03/21/2022 05:15 pm - SSN - Replaced
#  connectedServiceName: 'Pay-As-You-Go (d6723a94-6723-4e85-b988-03bf28d6ea51)'
  connectedServiceName: 'ssn-service-connection--default-web-centralus-20220321'
  

steps:
- task: DotNetCoreCLI@2

  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'
  enabled: true



- script: |

    cd DevSitesIndex
    npm install

  displayName: 'npm install root AngularJS'
  enabled: true



- script: |

    cd DevSitesIndex
    ssn_run_webpack_prod.cmd
 
  displayName: 'Build AngularJS'
  enabled: true

 

- script: |
    cd DevSitesIndex\timesheetsSupport7
    npm install
    
  displayName: 'npm install Angular 7'

- script: |
    cd DevSitesIndex\timesheetsSupport7
    ssn_build_prod

  displayName: 'npm build Angular 7'


# 04/12/2002 02:20 am - SSN

- script: |
    cd DevSitesIndex\ReactApp
    npm install

  displayName: 'npm install React'


- script: |
    cd DevSitesIndex\ReactApp
    ssn_run_webpack_prod

  displayName: 'npm build React'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'
  enabled: true


 

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
  enabled: true

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: $(WebAppName) '
  inputs:
    azureSubscription: '$(connectedServiceName)'
    appType: webApp
    appName: '$(WebAppName)'
    package: '$(build.artifactstagingdirectory)/**/*.zip'
  enabled: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  enabled: true
  
