
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: ssn-self-hosted-pool-20210604

variables:
  buildConfiguration: Release
  RestoreBuildProjects: '**/*.csproj'
  WebAppName: DevSitesIndex20190127
  connectedServiceName: 'Pay-As-You-Go (d6723a94-6723-4e85-b988-03bf28d6ea51)'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'
  enabled: false

- task: Npm@1
  displayName: 'npm install root'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install devsitesindex'
  enabled: false

- script: |
    cd devsitesindex
    npm install
    webpack
  displayName: 'npm install root 2'


- script: |
    cd devsitesindex
    webpack
  displayName: 'Webpack for AngularJS'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'
  enabled: false

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
  enabled: false

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: $(WebAppName) '
  inputs:
    azureSubscription: '$(connectedServiceName)'
    appType: webApp
    appName: '$(WebAppName)'
    package: '$(build.artifactstagingdirectory)/**/*.zip'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  enabled: false