
// 05/12/2022 09:13 pm - SSN

export const SIGNALR_CONSTANTS = {

    REQUEST_LOGIN: "SIGNALR_REQUEST_LOGIN",
    UPDATE_LOGIN_STATUS: "UPDATE_LOGIN_STATUS",
    REFRESH_DEVSITES_TIMELOG_LIST: "REFRESH_DEVSITES_TIMELOG_LIST",

    JOB_STATUS: {

        STARTING: "Starting",
        ALREADY_STARTED: "Already started",
        NOT_FOUND: "Job not found"

    },

    PROCESSOR_NAME: {
        REACTJS: "ReactJS"
    }

}